---
- name: Installer Docker (docker.io)
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: S'assurer que le service Docker est démarré
  service:
    name: docker
    state: started
    enabled: yes

- name: Ajouter l'utilisateur Ansible au groupe docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
